import { createElement } from 'lwc';
import EligibleProducts from 'c/eligibleProducts';

describe('c-eligible-products', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-eligible-products', {
            is: EligibleProducts
        });
        // Act
        document.body.appendChild(element);
        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });

    it('is accessible', async() => {
        // Arrange
        const element = createElement('c-eligible-products', {
            is: EligibleProducts
        });
        // Act
        document.body.appendChild(element);
        // Assert        
        await expect(element).toBeAccessible();
    });
});